# site properties and page defaults
title: CHENG Laboratory
subtitle: Epigenetics and Therapeutics in Immuno-Oncology
description: CHENG Laboratory of Epigenetics and Therapeutics in Immuno-Oncology, School of Biomedical Sciences, The Chinese University of Hong Kong
header: images/chromatin_structure.svg
footer: images/footer.png
proofer: false

# site social media and other links
links:
  email: alfredlabmailing@gmail.com
  orcid: 0000-0003-2345-6951
  google-scholar: Alfred S.L. Cheng
  github: ACLab-Bioinfo

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
